ix_name: "IIX-Jakarta"
api_summary_url: "https://squad.iix.net.id/api/v4/lg/rs1-ipv4/bgp-summary"
route_base_url: "https://squad.iix.net.id/lg/rs1-ipv4/routes/protocol/"
primary_output: "prefix.txt"
all_output: "all-prefix.txt"
concurrency: 10